In [1]:
import torch
from torch.autograd import Variable

In [2]:
# Variable in torch is to build a computational graph,
# but this graph is dynamic compared with a static graph in Tensorflow or Theano.
# So torch does not have placeholder, torch can just pass variable to the computational graph.

tensor = torch.FloatTensor([[1,2],[3,4]])            # build a tensor
variable = Variable(tensor, requires_grad=True)      # build a variable, usually for compute gradients

In [3]:
print(tensor)
print(variable)  

tensor([[ 1.,  2.],
        [ 3.,  4.]])
tensor([[ 1.,  2.],
        [ 3.,  4.]])


In [4]:
# till now the tensor and variable seem the same.
# However, the variable is a part of the graph, it's a part of the auto-gradient.

t_out = torch.mean(tensor*tensor)       # x^2
v_out = torch.mean(variable*variable)   # x^2
print(t_out)
print(v_out)    # 7.5

tensor(7.5000)
tensor(7.5000)


In [5]:
v_out.backward() # backpropagation from v_out

In [10]:
# v_out = 1/4 * sum(variable*variable)
# the gradients w.r.t the variable, d(v_out)/d(variable) = 1/4*2*variable = variable/2
print(variable.grad)

tensor([[ 0.5000,  1.0000],
        [ 1.5000,  2.0000]])


In [7]:
print(variable)     # this is data in variable format

tensor([[ 1.,  2.],
        [ 3.,  4.]])


In [8]:
print(variable.data) 

tensor([[ 1.,  2.],
        [ 3.,  4.]])


In [9]:
print(variable.data.numpy())

[[1. 2.]
 [3. 4.]]
